name: elearning_mobile
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  http: ^1.1.0
  shared_preferences: ^2.2.0
  jwt_decoder: ^2.0.1

  video_player: any
  youtube_player_flutter: any
  flutter_pdfview: any
  flutter_markdown: any
  url_launcher: any
  path_provider: any
  image_picker: any
  cached_network_image: any
  lucide_icons: ^0.257.0
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true